name: NASA Project CI                #name of the workflow
on:                                  #defines trigger this workflow will run
  push:                              #workflow will trigger when push to one of the below branches 
    branches: [ master ]             #our main branch is master 
  pull_request:                      #workflow will trigger when pull to one of the below branches
    branches: [ master ]
jobs:                                #workflow is made up one or more jobs will run when one of the event triggered(push,pull)
  build:     
    strategy:
      matrix: 
        node-version: [14.x, 16.x]                        #   
    runs-on: ubuntu-latest           #which os will run on
    steps:                           #we define list of action steps     
      - uses: actions/checkout@v2    #reusble script created by github
      - name: Use Node Js version ${{matrix.node-version}}  
        uses: actions/setup-node@v2  #setup node
        with:                        #with specific version     
          node-version: '${{matrix.node-version}}'
      - run: npm install             # 
      - run: npm run watch --prefix client          
      - run: npm test

  #depoloy:                         #if we deploy   